name: win32_clipboard
description: A package that provides a friendly Dart API for accessing the
  Windows Clipboard.
version: 0.1.2-wip
repository: https://github.com/halildurmus/win32_clipboard
issue_tracker: https://github.com/halildurmus/win32_clipboard/issues

topics:
  - clipboard
  - win32
  - ffi
  - windows

environment:
  sdk: ^3.3.0

platforms:
  windows:

dependencies:
  ffi: ^2.1.2
  win32: ^5.4.0

dev_dependencies:
  checks: ^0.3.0
  dartwindows_lints: ^1.1.0
  test: ^1.25.3
